Accueil page
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #10
Opened 2024-04-16 13:34 UTC by ozen2

2024-04-16 14:33 UTC, pjroggy commented on client/src/assets/images/ImageFondFixe.jpg
a supprimer

2024-04-16 14:33 UTC, pjroggy commented on client/src/assets/images/ImageFondMobil.png
a supprimer

2024-04-16 14:33 UTC, pjroggy commented on client/src/assets/images/Rectangle-44.svg
a supprimer

2024-04-16 14:33 UTC, pjroggy commented on client/src/assets/images/TerreMobil.jpg
a supprimer

2024-04-16 19:53 UTC, pjroggy commented on client/src/components/Slogan.jsx
> +    </section>
section or hgroup?

2024-04-16 19:57 UTC, pjroggy commented on client/src/styles/Footer.scss
> +    font-family: Varela Round;
use font from $font-family

2024-04-16 19:58 UTC, pjroggy commented on client/src/styles/Footer.scss
> +    color: white;
use $whiteColor: #fff8f0;

2024-04-16 20:00 UTC, pjroggy commented on client/src/styles/Header.scss
> +    font-family: Varela Round;
use $headerFont: "Tomorrow", sans-serif;

2024-04-16 20:01 UTC, pjroggy commented on client/src/styles/Header.scss
> +    font-family: Tomorrow;
use $headerFont: "Tomorrow", sans-serif;

2024-04-16 20:01 UTC, pjroggy commented on client/src/styles/Header.scss
> +  color: white;
use $whiteColor: #fff8f0;

2024-04-16 20:02 UTC, pjroggy commented on client/src/styles/HomeCards.scss
> +  font-family: Varela Round;
use $bodyFont: "Varela Round", sans-serif;

2024-04-16 20:03 UTC, pjroggy commented on client/src/styles/HomeCards.scss
> +      color: white;
use $whiteColor: #fff8f0;

2024-04-16 20:03 UTC, pjroggy commented on client/src/styles/HomeCards.scss
> +      font-family: Varela Round;
use $bodyFont: "Varela Round", sans-serif;

2024-04-16 20:04 UTC, pjroggy commented on client/src/styles/HomeCards.scss
> +    font-family: Varela Round;
use $bodyFont: "Varela Round", sans-serif;

2024-04-16 20:04 UTC, pjroggy commented on client/src/styles/Links.scss
>      font-family: Varela Round;
use $bodyFont: "Varela Round", sans-serif;

2024-04-16 20:06 UTC, pjroggy commented on client/src/styles/app.scss
>  * {
may be can we use html instead of *

2024-04-17 08:36 UTC, Yoann-Fortin requested changes

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/components/Header.jsx
> +    <hgroup className="titleSlider">
Wrong use with this tag

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/components/HomeCards.jsx
> +          <hgroup>
Wrong uses to this html tag

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/components/HomeCards.jsx
> +      <section className="allCards">
Why section in section tag without title ?

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/components/Slogan.jsx
> +    <section className="slogan">
Wrong uses to this tags

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/pages/Home.jsx
> +        <Header planetName="Neptune" />
The component name isn't ideal, or you'd have to use the header tag in the component.

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/pages/Home.jsx
Why use header anf footer component here and not in your App component ?

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/styles/Footer.scss
> +@media screen and (min-width: 320px) {
Wrong use of this media query

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/styles/Header.scss
> +  color: white;
exactly

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/components/HomeCards.jsx
> +            <img id="left" src={imageLeft} alt="" />
Why use id here ?

2024-04-17 08:36 UTC, Yoann-Fortin commented on client/src/styles/app.scss
> +    background-size: cover;
duplicate code

2024-04-17 10:12 UTC, closed without merging