FeatureB, miss component DropDownTraveller
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #13
Opened 2024-04-17 23:30 UTC by adrale

2024-04-18 08:54 UTC, Gamarin0 commented on client/src/App.jsx
> +          {/* <p>Nombre de passagers : {reservationData.selectedTravellerCount}</p> */}
l87 to l92 -> needed without other components, to be deleted after.

2024-04-18 08:54 UTC, Gamarin0 commented on client/src/components/ReservationModule.jsx
> +// import DropDownTraveller from "./DropDownTraveller";
Waiting for PR approuval of this componant

2024-04-18 08:54 UTC, Gamarin0 commented on client/src/components/ReservationModule.jsx
> +    <form onSubmit={handleSubmit}>
fieldset tag + legend tag required

2024-04-18 08:54 UTC, Gamarin0 commented on client/src/components/Arrival.jsx
> +      <select
datalist tag would be better here

2024-04-18 08:54 UTC, Gamarin0 commented on client/src/components/Departure.jsx
> +      <select
datalist tag would be better here

2024-04-18 13:04 UTC, Yoann-Fortin requested changes

2024-04-18 13:04 UTC, Yoann-Fortin commented on client/src/App.jsx
> +import ReservationForm from "./components/ReservationModule";
Fix typo please

2024-04-18 13:04 UTC, Yoann-Fortin commented on client/src/components/Arrival.jsx
> +  const handleSelectSuggestion = (event) => {
Dead code here

2024-04-18 13:04 UTC, Yoann-Fortin commented on client/src/components/Arrival.jsx
> +    <div>
Why this div ?

2024-04-18 13:04 UTC, Yoann-Fortin commented on client/src/components/Arrival.jsx
> +        <option value="" disabled hidden>
Can you explain me this line ?

2024-04-18 13:04 UTC, Yoann-Fortin commented on client/src/components/DateSelect.jsx
> +  const [departureDate, setDepartureDate] = useState("");
Dead code

2024-04-18 13:04 UTC, Yoann-Fortin commented on client/src/components/DateSelect.jsx
> +    const selectedDate = event.target.value;
And here

2024-04-18 13:04 UTC, Yoann-Fortin commented on client/src/components/DateSelect.jsx
> +    <div>
Why this tag ?

2024-04-18 13:04 UTC, Yoann-Fortin commented on client/src/components/Departure.jsx
Same component but repeat ?

2024-04-18 13:26 UTC, adrale commented on client/src/components/Arrival.jsx
> +        <option value="" disabled hidden>
To have an Default Value but unusable by the user

2024-04-19 15:55 UTC, Yoann-Fortin requested changes

2024-04-19 15:55 UTC, Yoann-Fortin commented on client/src/components/DestinationSelect.jsx
> +      <div>
Why use a div tag here ?

2024-04-19 15:55 UTC, Yoann-Fortin commented on client/src/components/ReservationModule.jsx
> +// import DropDownTraveller from "./DropDownTraveller";
commented code is prohibited

2024-04-19 15:55 UTC, Yoann-Fortin commented on client/src/components/ReservationModule.jsx
> +      {/* <DropDownTraveller onChange={(count) => handleInputChange('selectedTravellerCount', count)} /> */}
same here

2024-04-22 07:57 UTC, Yoann-Fortin approved these changes

2024-04-22 08:06 UTC, Yoann-Fortin approved these changes

2024-04-22 08:06 UTC, merged