Finishing ContactForm
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #18
Opened 2024-04-21 16:38 UTC by adrale

2024-04-22 08:02 UTC, Gamarin0 requested changes

2024-04-22 08:02 UTC, Gamarin0 commented on client/src/components/ContactForm.jsx
> +        required
Missing message input :(

2024-04-23 12:22 UTC, KevinDavoust commented on client/src/components/ContactForm.jsx
> +        placeholder="Votre message ..."
placeholder en français alors que l'alerte à la soumission du formulaire est en anglais ? un peu de sérieux et de cohérence voyons....................................

2024-04-24 07:26 UTC, FabienRollet approved these changes

2024-04-24 07:40 UTC, KevinDavoust approved these changes

2024-04-24 07:40 UTC, merged