merge dev main
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #30
Opened 2024-04-25 13:48 UTC by ozen2

2024-04-28 23:27 UTC, adrale approved these changes

2024-04-29 08:44 UTC, ozen2 commented on client/src/components/TopPlanet.jsx
> +  fetch("https://api.star-citizen.wiki/api/galactapedia/VarZxj1Qav")
change this id

2024-04-29 08:45 UTC, pjroggy requested changes

2024-04-29 08:45 UTC, pjroggy commented on client/src/components/TopPlanet.jsx
> +  fetch("https://api.star-citizen.wiki/api/galactapedia/VarZxj1Qav")
change id of planet to Rvl7EggdAr

2024-04-29 09:58 UTC, Gamarin0 approved these changes

2024-04-29 09:58 UTC, FabienRollet commented on client/src/assets/images/carlos-kenobi-Knla5kYvsRE-unsplash.jpg
No use for this pic anymore

2024-04-29 09:58 UTC, FabienRollet commented on client/src/assets/images/daniel-olah-16XJMQ2bTl4-unsplash.jpg
same

2024-04-29 09:58 UTC, FabienRollet commented on client/src/assets/images/pawel-czerwinski-fAd4u_HTGGY-unsplash (1).jpg
same

2024-04-29 09:58 UTC, FabienRollet commented on client/src/assets/images/solen-feyissa-AI9Z8vNLcKc-unsplash.jpg
same (for this file and the next one

2024-04-29 15:16 UTC, pjroggy approved these changes

2024-04-29 15:17 UTC, lxndrMr approved these changes

2024-04-30 08:31 UTC, Yoann-Fortin commented on client/src/components/JourneyDetails.jsx
> +  const handleClick = () => {
Dead code

2024-04-30 08:31 UTC, Yoann-Fortin commented on client/src/pages/Booking.jsx
> +    <main>
Both main, the first is in App.jsx

2024-04-30 08:31 UTC, Yoann-Fortin commented on client/src/pages/ErrorPage.jsx
> +    <body className="error404Body">
Not possible

2024-04-30 08:31 UTC, merged