Nesrine/vehicule
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #39
Opened 2024-04-28 22:46 UTC by NESRINERABAAOUI

2024-04-28 23:53 UTC, adrale requested changes

2024-04-28 23:53 UTC, adrale commented on client/src/components/Home.jsx
> +  return <div style={{ backgroundColor: "purple", height: "84dvh" }}>HOME</div>;
You mean "84vh" ?

2024-04-28 23:53 UTC, adrale commented on client/.prettierrc
> +  "trailingComma": "all",
Restore the basic parameter

2024-04-28 23:53 UTC, adrale commented on client/src/components/Info.jsx
> +  return <div style={{ backgroundColor: "blue", height: "84dvh" }}>Info</div>;
You mean "84vh" ?

2024-04-28 23:53 UTC, adrale commented on client/src/components/NavBar.jsx
> +              {" "}
Remove comment

2024-04-28 23:53 UTC, adrale commented on client/src/components/Voyage.jsx
> +  return <div>Voyage</div>;
Why use div?

2024-04-28 23:53 UTC, adrale commented on client/src/components/Vehicule.jsx
> +      <div className="cards">
Why use div?

2024-04-28 23:53 UTC, adrale commented on client/src/components/Vehicule.jsx
> +          <div key={vehicule.id} className="cardVehicule">
Why use div?

2024-04-28 23:53 UTC, adrale commented on client/src/components/Vehicule.jsx
> +            <div className="carac">
Why use div?

2024-04-28 23:53 UTC, adrale commented on client/src/components/Vehicule.jsx
> +        <div className="divWidth">
same

2024-04-28 23:53 UTC, adrale commented on client/src/components/Vehicule.jsx
> +              <div className="generic" key={slideImage.caption}>
same

2024-04-28 23:53 UTC, adrale commented on client/src/components/Info.jsx
> +  return <div style={{ backgroundColor: "blue", height: "84dvh" }}>Info</div>;
Why use div?

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +  width: 100dvw;
You mean "100vw" ?

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +  width: 30dvw;
You mean "30vw" ?

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +  margin-top: 4dvh;
You mean "4vh" ?

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +  margin-top: 4dvh;
i think "rem" it's better

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +  height: 15 rem;
no space between 15rem

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +  margin-top: 3dvh;
i think "rem" it's better

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +  margin-top: 4dvh;
same

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +    margin-top: 11dvh;
i think "rem" it's better

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +    height: 15 rem;
no space between 15rem

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +  height: 30dvh;
You mean "30vh" ?

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +  width: 30dvw;
You mean "30vw" ?

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +    width: 90dvw;
You mean "90vw" ?

2024-04-28 23:53 UTC, adrale commented on client/src/styles/Vehicules.scss
> +    width: 80dvw;
You mean "80vw" ?

2024-04-29 07:19 UTC, ozen2 commented on client/.prettierrc
> +  "trailingComma": "all",
yes

2024-04-29 07:19 UTC, ozen2 commented on client/src/components/Home.jsx
> +  return <div style={{ backgroundColor: "purple", height: "84dvh" }}>HOME</div>;
div ?????

2024-04-29 07:19 UTC, ozen2 commented on client/src/components/NavBar.jsx
> +              {" "}
why { " " } ?

2024-04-29 07:19 UTC, ozen2 commented on client/src/components/Vehicule.jsx
> +      <div className="cards">
div ????

2024-04-29 07:19 UTC, ozen2 commented on client/src/components/Vehicule.jsx
> +          <div key={vehicule.id} className="cardVehicule">
div ????

2024-04-29 07:19 UTC, ozen2 commented on client/src/components/Vehicule.jsx
> +            <div className="carac">
div ???

2024-04-29 07:19 UTC, ozen2 commented on client/src/components/Vehicule.jsx
> +        <div className="divWidth">
div ?????

2024-04-29 07:19 UTC, ozen2 commented on client/src/components/Vehicule.jsx
> +              <div className="generic" key={slideImage.caption}>
not div !!!!!

2024-04-29 07:19 UTC, ozen2 commented on client/src/components/Voyage.jsx
> +  return <div>Voyage</div>;
no div !!!!!!!!!!!

2024-04-29 07:19 UTC, ozen2 commented on client/src/main.jsx
> +import vehicules from "./db/VehiculesDb";
component double

2024-04-29 07:19 UTC, ozen2 commented on client/src/styles/Vehicules.scss
> +  width: 100dvw;
yeah ??

2024-04-29 07:19 UTC, ozen2 commented on client/src/styles/Vehicules.scss
> +  width: 30dvw;
same

2024-04-29 07:19 UTC, ozen2 commented on client/src/styles/Vehicules.scss
> +  margin-top: 4dvh;
we said we work with rem

2024-04-29 07:19 UTC, ozen2 commented on client/src/styles/Vehicules.scss
> +  height: 15 rem;
yes

2024-04-29 07:19 UTC, ozen2 commented on client/src/styles/Vehicules.scss
> +  margin-top: 3dvh;
same

2024-04-29 07:19 UTC, ozen2 commented on package-lock.json
why this file changed ??

2024-04-29 07:19 UTC, ozen2 commented on package.json
and this file ???

2024-04-29 13:17 UTC, pjroggy approved these changes

2024-04-29 13:18 UTC, adrale approved these changes

2024-04-29 13:37 UTC, Yoann-Fortin requested changes

2024-04-29 13:37 UTC, Yoann-Fortin commented on client/src/components/Home.jsx
This component is not update with rest code

2024-04-29 13:37 UTC, Yoann-Fortin commented on client/src/components/NavBar.jsx
> +            <Link to="/OurVehicles" aria-label="link to the Traffic info page">
attribut aria-label do not correspond with this real redirection

2024-04-29 13:37 UTC, Yoann-Fortin commented on client/src/components/Voyage.jsx
Not necessary  component

2024-04-29 15:00 UTC, Yoann-Fortin approved these changes

2024-04-29 15:00 UTC, merged