add error page
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #4
Opened 2024-04-12 11:59 UTC by pjroggy

2024-04-12 15:01 UTC, KevinDavoust approved these changes

2024-04-15 13:18 UTC, Yoann-Fortin requested changes

2024-04-15 13:18 UTC, Yoann-Fortin commented on client/src/pages/ErrorPage.jsx
> +    <section className="error404">
Main tag is better here

2024-04-15 13:18 UTC, Yoann-Fortin commented on client/src/pages/ErrorPage.jsx
> +      <h2>Trou de ver E404</h2>
H1 is better here also

2024-04-15 13:18 UTC, Yoann-Fortin commented on client/src/styles/ErrorPage404.scss
> +  align-content: center;
Dead code here

2024-04-15 13:18 UTC, Yoann-Fortin commented on client/src/styles/ErrorPage404.scss
> +  color: white;
A color variable is already declared but unused here

2024-04-15 13:18 UTC, Yoann-Fortin commented on client/src/styles/ErrorPage404.scss
> +  color: white;
Same

2024-04-15 13:18 UTC, Yoann-Fortin commented on client/src/styles/ErrorPage404.scss
> +  margin: 10px;
rem is used in this project

2024-04-16 11:59 UTC, adrale approved these changes

2024-04-17 08:15 UTC, Yoann-Fortin requested changes

2024-04-17 08:15 UTC, Yoann-Fortin commented on client/src/App.css
No empty file please

2024-04-17 08:42 UTC, pjroggy commented on client/src/App.css
done !!

2024-04-18 13:30 UTC, Yoann-Fortin approved these changes

2024-04-19 15:59 UTC, Yoann-Fortin approved these changes

2024-04-22 08:07 UTC, Yoann-Fortin approved these changes

2024-04-22 08:07 UTC, merged