add selection of trip type
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #6
Opened 2024-04-14 16:37 UTC by pjroggy

2024-04-14 20:12 UTC, adrale approved these changes

2024-04-15 13:45 UTC, Yoann-Fortin requested changes

2024-04-15 13:45 UTC, Yoann-Fortin commented on client/src/styles/DropdownRoundTrip.scss
> +  background-color: #fff8f0;
variable should be used here

2024-04-15 13:45 UTC, Yoann-Fortin commented on client/src/styles/DropdownRoundTrip.scss
> +  background-color: #fff8f0;
same

2024-04-15 13:45 UTC, Yoann-Fortin commented on client/src/styles/DropdownRoundTrip.scss
> +  background-color: #fff8f0;
same

2024-04-16 11:18 UTC, adrale approved these changes

2024-04-17 08:18 UTC, Yoann-Fortin approved these changes

2024-04-17 08:18 UTC, merged