Add component Arrival
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #7
Opened 2024-04-14 18:24 UTC by adrale

2024-04-14 20:51 UTC, Gamarin0 approved these changes

2024-04-14 21:08 UTC, pjroggy approved these changes

2024-04-15 13:34 UTC, Yoann-Fortin requested changes

2024-04-15 13:34 UTC, Yoann-Fortin commented on client/src/components/Arrival.jsx
> +    const[selectedArrival, SetSelectedArrival] = useState('')
Not a uppercase to method

2024-04-15 13:34 UTC, Yoann-Fortin commented on client/src/components/Arrival.jsx
> +        SetSelectedArrival(e.target.value)
same

2024-04-15 13:34 UTC, Yoann-Fortin commented on client/src/components/Arrival.jsx
> +            <input
missing id attribute

2024-04-17 08:17 UTC, Yoann-Fortin approved these changes

2024-04-17 08:17 UTC, merged