Add component to choose date
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #8
Opened 2024-04-14 19:10 UTC by adrale

2024-04-14 20:44 UTC, Gamarin0 approved these changes
J'ai juste rajouté les date par défaut dans le calendrier (année 2948 au lieu de 2024)

2024-04-14 21:03 UTC, pjroggy approved these changes

2024-04-15 13:32 UTC, Yoann-Fortin requested changes

2024-04-15 13:32 UTC, Yoann-Fortin commented on client/src/components/DateSelect.jsx
> +    const [DepartureDate, setDepartureDate] = useState('');
Not a class ou functionnal component to initialize state

2024-04-15 13:32 UTC, Yoann-Fortin commented on client/src/components/DateSelect.jsx
> +            <input
missing attribut id

2024-04-17 08:16 UTC, Yoann-Fortin approved these changes

2024-04-17 08:16 UTC, merged