Add component Departure
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_nebula pull request #9
Opened 2024-04-14 20:09 UTC by adrale

2024-04-14 20:49 UTC, Gamarin0 approved these changes

2024-04-14 21:07 UTC, pjroggy approved these changes

2024-04-15 13:28 UTC, Yoann-Fortin requested changes

2024-04-15 13:28 UTC, Yoann-Fortin commented on client/src/components/Departure.jsx
> +    const[selectedDeparture, SetSelectedDeparture] = useState('')
Are you sure ? Not use a class or a functionnal component to a function

2024-04-15 13:28 UTC, Yoann-Fortin commented on client/src/components/Departure.jsx
> +        SetSelectedDeparture(e.target.value)
same

2024-04-15 13:28 UTC, Yoann-Fortin commented on client/src/components/Departure.jsx
> +            <label htmlFor="Departure">Arrivée à :</label>
missing id in input and no uppercase in the start of your value

2024-04-15 13:28 UTC, Yoann-Fortin commented on client/src/components/Departure.jsx
> +            <input
missing attribut id to link with the correct label

2024-04-16 10:27 UTC, pjroggy approved these changes

2024-04-17 08:15 UTC, Yoann-Fortin approved these changes

2024-04-17 08:15 UTC, merged